-- a 
SELECT * FROM ARTICLE ORDER BY DESIGNATION ASC;
-- b 
SELECT * FROM ARTICLE ORDER BY PRIX DESC;
-- c 
SELECT * FROM ARTICLE WHERE DESIGNATION LIKE "%Boulon%" ORDER BY PRIX DESC;
-- d 
SELECT DESIGNATION FROM ARTICLE WHERE DESIGNATION LIKE "%Sachet%";
-- e 
SELECT DESIGNATION FROM ARTICLE WHERE LOWER(DESIGNATION) LIKE "%Sachet%";
-- f
SELECT A.REF, A.DESIGNATION, A.PRIX, F.NOM AS FOURNISSEUR
FROM ARTICLE A
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
ORDER BY F.NOM ASC, A.PRIX DESC;

-- g
SELECT * FROM ARTICLE WHERE ID_FOU 
IN (SELECT ID FROM fournisseur WHERE NOM = "Dubois & Fils")

-- h
SELECT AVG(PRIX) FROM ARTICLE WHERE ID_FOU 
IN (SELECT ID FROM fournisseur WHERE NOM = "Dubois & Fils") 

-- i
SELECT F.NOM AS Fournisseur, AVG(A.PRIX) AS MoyennePrix
FROM ARTICLE A
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
GROUP BY F.NOM;
