-- a 
SELECT * FROM ARTICLE ORDER BY DESIGNATION ASC;
-- b 
SELECT * FROM ARTICLE ORDER BY PRIX DESC;
-- c 
SELECT * FROM ARTICLE WHERE DESIGNATION LIKE "%Boulon%" ORDER BY PRIX DESC;
-- d 
SELECT DESIGNATION FROM ARTICLE WHERE DESIGNATION LIKE "%Sachet%";
-- e 
SELECT DESIGNATION FROM ARTICLE WHERE LOWER(DESIGNATION) LIKE "%Sachet%";
-- f
SELECT A.REF, A.DESIGNATION, A.PRIX, F.NOM AS FOURNISSEUR
FROM ARTICLE A
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
ORDER BY F.NOM ASC, A.PRIX DESC;

-- g
SELECT * FROM ARTICLE WHERE ID_FOU 
IN (SELECT ID FROM fournisseur WHERE NOM = "Dubois & Fils")

-- h
SELECT AVG(PRIX) FROM ARTICLE WHERE ID_FOU 
IN (SELECT ID FROM fournisseur WHERE NOM = "Dubois & Fils") 

-- i
SELECT F.NOM AS FOURNISSEUR, AVG(A.PRIX) AS MoyennePrix
FROM ARTICLE A
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
GROUP BY F.NOM;

-- j
SELECT * FROM BON WHERE DATE_CMDE BETWEEN '2019-03-01' AND '2019-04-05 12:00:00';

-- k
SELECT DISTINCT BON.* FROM BON 
JOIN COMPO C ON BON.ID = C.ID_BON
JOIN ARTICLE A ON C.ID_ART = A.ID  
WHERE A.DESIGNATION LIKE "%Boulon%" ;

-- l
SELECT DISTINCT B.ID, B.NUMERO, B.DATE_CMDE, B.DELAI, F.NOM AS NOM_FOURNISSEUR
FROM BON B
JOIN COMPO C ON B.ID = C.ID_BON
JOIN ARTICLE A ON C.ID_ART = A.ID
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
WHERE A.DESIGNATION LIKE '%boulon%';

--m AVG(A.PRIX) AS MoyennePrix
SELECT B.ID, B.NUMERO, B.DATE_CMDE, B.DELAI, F.NOM AS NOM_FOURNISSEUR, SUM(A.PRIX) AS PRIX_TOTAL
FROM BON B
JOIN COMPO C ON B.ID = C.ID_BON
JOIN ARTICLE A ON 
WHERE 

-- n
SELECT B.ID, B.NUMERO, B.DATE_CMDE, B.DELAI, F.NOM AS NOM_FOURNISSEUR, SUM(A.PRIX) AS PRIX_TOTAL
FROM BON B
JOIN COMPO C ON B.ID = C.ID_BON
JOIN ARTICLE A ON C.ID_ART = A.ID
JOIN FOURNISSEUR F ON A.ID_FOU = F.ID
GROUP BY B.ID, B.NUMERO, B.DATE_CMDE, B.DELAI, F.NOM;
