-- 3-a
UPDATE ARTICLE
SET DESIGNATION = UPPER(DESIGNATION)
WHERE PRIX > 10;

-- 3-b
UPDATE ARTICLE
SET DESIGNATION = LOWER(DESIGNATION)
WHERE ARTICLE.ID = 2;

--3-c
UPDATE ARTICLE
SET PRIX = PRIX * 1.1
WHERE ID_FOU = 2;
