-- a)
SELECT * FROM ARTICLE ORDER BY DESIGNATION ;

-- b)
SELECT * FROM ARTICLE ORDER BY PRIX DESC ;

-- c)
SELECT * FROM ARTICLE WHERE DESIGNATION LIKE '%Boulon%' ORDER BY PRIX ;

-- d)
SELECT * FROM ARTICLE WHERE DESIGNATION LIKE '%sachet%';

-- e)
SELECT * FROM ARTICLE WHERE DESIGNATION LIKE '%sachet%';

-- f)
SELECT * FROM ARTICLE
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
ORDER BY FOURNISSEUR.NOM, ARTICLE.PRIX DESC
;

-- g)
SELECT * FROM ARTICLE
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE FOURNISSEUR.NOM LIKE 'Dubois & Fils'
ORDER BY FOURNISSEUR.NOM, ARTICLE.PRIX DESC
;

-- h)
SELECT AVG(PRIX) AS 'MOYENNE DE PRIX DUBOIS & FILS' FROM ARTICLE
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE FOURNISSEUR.NOM LIKE 'Dubois & Fils'
GROUP BY FOURNISSEUR.NOM
ORDER BY FOURNISSEUR.NOM, ARTICLE.PRIX DESC
;

-- i)
SELECT FOURNISSEUR.NOM, AVG(PRIX) AS 'MOYENNE DE PRIX' FROM ARTICLE
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
GROUP BY FOURNISSEUR.NOM
ORDER BY FOURNISSEUR.NOM, ARTICLE.PRIX DESC
;

-- j)
SELECT * FROM BON
WHERE DATE_CMDE BETWEEN '2019-03-01 00:00:00' AND '2019-04-05 12:00:00';

-- k)
SELECT BON.ID AS 'NUMERO_DE_BON' FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
WHERE DESIGNATION LIKE '%boulon%'
GROUP BY 'NUMERO_DE_BON'
;

-- l)
SELECT BON.ID AS 'NUMERO_DE_BON', FOURNISSEUR.NOM FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
INNER JOIN FOURNISSEUR ON FOURNISSEUR.ID = BON.ID_FOU
WHERE DESIGNATION LIKE '%boulon%'
;

-- m)
SELECT BON.ID AS 'NUMERO_DE_BON', SUM(PRIX) AS 'PRIX_TOTAL' FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
INNER JOIN FOURNISSEUR ON FOURNISSEUR.ID = BON.ID_FOU
GROUP BY BON.ID
;

-- n)
SELECT BON.ID AS 'NUMERO_DE_BON', COUNT(ID_ART) AS 'NB_ARTICLES' FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
INNER JOIN FOURNISSEUR ON FOURNISSEUR.ID = BON.ID_FOU
GROUP BY BON.ID
;

-- o)







