-- 3a)
UPDATE ARTICLE 
SET DESIGNATION = UPPER(DESIGNATION)
WHERE PRIX > 10;

-- 3b)
UPDATE ARTICLE 
SET DESIGNATION = LOWER(DESIGNATION)
WHERE ID=2;

-- 3c)
UPDATE ARTICLE 
SET PRIX = 1.1*PRIX
WHERE ID_FOU=2;