CREATE TABLE ARTICLE (
    ID INT(30) PRIMARY KEY,
    REF VARCHAR(50),
    DESIGNATION VARCHAR(50),
    PRIX DECIMAL(10),
    ID_FOU INT(30)
    );

CREATE TABLE FOURNISSEUR (
    ID INT(30) PRIMARY KEY,
    NOM VARCHAR(50)
    );
    
CREATE TABLE BON (
    ID INT(30) PRIMARY KEY,
    NUMERO INT(30),
    DATE_CMDE DATE,
    DELAI INT(30),
    ID_FOU INT(30)
    );

CREATE TABLE COMPO (
    ID INT(30) AUTO_INCREMENT PRIMARY KEY,
    QTE INT(30),
    ID_ART INT(30),
    ID_BON INT(30)
    );
