CREATE TABLE ARTICLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    REF VARCHAR(255) UNIQUE NOT NULL,
    DESIGNATION VARCHAR(255) NOT NULL,
    PRIX DECIMAL(6, 2) NOT NULL,
    ID_FOU INT
);

CREATE TABLE FOURNISSEUR (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(50) NOT NULL
);

CREATE TABLE BON (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO VARCHAR(120) UNIQUE NOT NULL,
    DATE_CMDE DATE ,
    DELAI TIME ,
    ID_FOU INT
);

CREATE TABLE COMPO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    QTE INT NOT NULL,
    ID_ART INT,
    ID_BON INT
);

ALTER TABLE ARTICLE
ADD CONSTRAINT fk_article_fournisseur
FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);

ALTER TABLE BON
ADD CONSTRAINT fk_bon_fournisseur
FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID);

ALTER TABLE COMPO
ADD CONSTRAINT fk_compo_article
FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID);

ALTER TABLE COMPO
ADD CONSTRAINT fk_compo_bon
FOREIGN KEY (ID_BON) REFERENCES BON(ID);