-- 2 )

--a)
SELECT * 
FROM ARTICLE
WHERE ID ORDER BY DESIGNATION ASC ;

--b)
SELECT * 
FROM ARTICLE
WHERE ID ORDER BY PRIX DESC ;

--c)
SELECT * 
FROM ARTICLE
WHERE DESIGNATION LIKE '%Boulon%' ORDER BY PRIX ASC  ;

--d)
SELECT * 
FROM ARTICLE
WHERE DESIGNATION LIKE '%sachet%';

--e)
SELECT * 
FROM ARTICLE
WHERE DESIGNATION LIKE '%Sachet%';

--f)
SELECT *  
FROM ARTICLE
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
ORDER BY FOURNISSEUR.NOM, ARTICLE.PRIX DESC;


--g)
SELECT *  
FROM ARTICLE
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE FOURNISSEUR.NOM LIKE '%Dubois & Fils%'
ORDER BY FOURNISSEUR.NOM, ARTICLE.PRIX DESC;

--h)
SELECT FOURNISSEUR.NOM,AVG(PRIX) 
FROM ARTICLE
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE FOURNISSEUR.NOM LIKE '%Dubois & Fils%'
GROUP BY FOURNISSEUR.NOM
ORDER BY FOURNISSEUR.NOM, ARTICLE.PRIX DESC;

--i)
SELECT FOURNISSEUR.NOM,AVG(PRIX)
FROM ARTICLE
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
GROUP BY FOURNISSEUR.NOM
ORDER BY FOURNISSEUR.NOM, ARTICLE.PRIX DESC;

--j)
SELECT * 
FROM BON
WHERE DATE_CMDE BETWEEN '2019-03-01 12:00:00' AND '2019-04-05 12:00:00' ;

--k)
SELECT * 
FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
WHERE ARTICLE.DESIGNATION LIKE '%Boulon%' ;

--l)
SELECT FOURNISSEUR.NOM,ARTICLE.DESIGNATION 
FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE ARTICLE.DESIGNATION LIKE '%Boulon%' 
GROUP BY FOURNISSEUR.NOM;

--m)
SELECT BON.NUMERO,SUM(ARTICLE.PRIX)
FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
GROUP BY BON.ID;

--n)
SELECT BON.NUMERO,SUM(COMPO.QTE)
FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
GROUP BY BON.ID;

--o)
SELECT BON.NUMERO,SUM(COMPO.QTE)
FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
GROUP BY BON.ID
HAVING SUM(COMPO.QTE) > 25 ;

--p)
SELECT SUM(PRIX) AS 'COUT_TOT_CMDE'
FROM COMPO
INNER JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
INNER JOIN BON ON COMPO.ID_BON = BON.ID
INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE DATE_CMDE BETWEEN '2019-04-01 00:00:00' AND '2019-04-30 23:59:59' ;


